### ISSUE TITLE
Error:No such property: GradleVersion for class: JetGradlePlugin

### ISSUE THREAD

**Issue by iszengmh** [nekolr/sirius-inc#3]
idea报Error:No such property: GradleVersion for class: JetGradlePlugin，伸手党有释放版吗
```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-5.4.1-bin.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
```

**Comment by iszengmh** [comment]
下载gradle4.0版本，将file-setting-Build,Execution,Deployment-gradle中修改为4.0版本即可
![image](https://user-images.githubusercontent.com/16217979/58395077-10a29780-8079-11e9-8b6b-68174c8f8781.png)

**Comment by nekolr** [comment]
谢谢你的反馈，一会儿我会释出可以直接使用的打包版本
