### ISSUE TITLE
所有依赖项均提示程序包不存在

### ISSUE THREAD

**Issue by iszengmh** [nekolr/sirius-inc#4]
所有通过gradle的依赖包均提示不存在，已经build成功了，不知道怎么回事，不知道是不是阿里云的仓库有问题
```
Error:(3, 25) java: 程序包cn.hutool.core.io不存在
Error:(4, 27) java: 程序包cn.hutool.core.util不存在
Error:(101, 55) java: 找不到符号
  符号:   方法 getSvnChangelogOutPath()
  位置: 类型为com.nekolr.model.Setting的变量 setting
Error:(103, 27) java: 找不到符号
  符号:   方法 getSvnChangelogOutPath()
  位置: 类型为com.nekolr.model.Setting的变量 setting
```

**Comment by nekolr** [comment]
> 
> 
> 所有通过gradle的依赖包均提示不存在，已经build成功了，不知道怎么回事，不知道是不是阿里云的仓库有问题
> 
> ```
> Error:(3, 25) java: 程序包cn.hutool.core.io不存在
> Error:(4, 27) java: 程序包cn.hutool.core.util不存在
> Error:(101, 55) java: 找不到符号
>   符号:   方法 getSvnChangelogOutPath()
>   位置: 类型为com.nekolr.model.Setting的变量 setting
> Error:(103, 27) java: 找不到符号
>   符号:   方法 getSvnChangelogOutPath()
>   位置: 类型为com.nekolr.model.Setting的变量 setting
> ```

IDEA 需要安装配置 lombok 插件，具体操作可以网上搜索一下

**Comment by iszengmh** [comment]
我有装插件的，刚才更新了插件，也不行，应该不是插件的问题

**Comment by nekolr** [comment]
> 
> 
> 我有装插件的，刚才更新了插件，也不行，应该不是插件的问题

在 gradle 4.7 前后，lombok 插件引入的方式是不同的。你可以加我，我先提供你打包的版本。微信：RXhjYWxpbWF4

**Comment by iszengmh** [comment]
> > 我有装插件的，刚才更新了插件，也不行，应该不是插件的问题
> 
> 在 gradle 4.7 前后，lombok 插件引入的方式是不同的。你可以加我，我先提供你打包的版本。微信：RXhjYWxpbWF4

你微信查不到

**Comment by iszengmh** [comment]
> > 我有装插件的，刚才更新了插件，也不行，应该不是插件的问题
> 
> 在 gradle 4.7 前后，lombok 插件引入的方式是不同的。你可以加我，我先提供你打包的版本。微信：RXhjYWxpbWF4

加我吧emVuZ21pYW5odWk=
